### ISSUE TITLE
Make the "Select a playlist" option more obvious

### ISSUE THREAD

**Issue by Deinonychus71** [Deinonychus71/Sma5hMusic#21]
Apparently some people are struggling with what to do to add songs to playlists, so make it more obvious I guess.

**Comment by Segtendo** [comment]
Idea: after you get finished adding a song, could the program say something like:

`Song added successfully! Would you like to add it to a playlist?`

Would, hopefully, resolve some of the issues.

**Comment by Deinonychus71** [comment]
Ok but how do you select the playlist from there?

**Comment by Segtendo** [comment]
Maybe after selecting yes, have a dropdown menu to choose the playlist?

Or automatically open the playlist dropdown menu to get the user's attention?

**Comment by Deinonychus71** [comment]
Implemented for testing as part of 1.54b. Closing.
