### ISSUE TITLE
Small text for song titles + others?

### ISSUE THREAD

**Issue by Segtendo** [Deinonychus71/Sma5hMusic#22]
When looking in to how the game handles the small text, I found how to do it via editing a default song. Having a field to do this would be great.

`\u000e\u0000\u0002\u0002P(PUT TEXT HERE)\u000e\u0000\u0002\u0002d`

In the program, it will look like this:
![image](https://user-images.githubusercontent.com/76792055/103516671-8581aa00-4e36-11eb-81d1-a27281efb2a3.png)

When seeing it in-game, it looks like this:
![image](https://user-images.githubusercontent.com/76792055/103516717-93cfc600-4e36-11eb-8c1f-4e02a6c9bfc5.png)

As shown here, putting `\u000e\u0000\u0002\u0002P` and `\u000e\u0000\u0002\u0002d` with some text in the middle will provide the shown results.

This is the only thing I've found out about song titles. If anyone else has anything to add, feel free.

**Comment by Deinonychus71** [comment]
Do you know if there are other special tags like that?
