### ISSUE TITLE
Sound Test Visibility bug

### ISSUE THREAD

**Issue by Segtendo** [Deinonychus71/Sma5hMusic#23]
When editing the visibility of the song, the program won't switch accordingly when choosing something from the dropdown menus on the side. Video included.

https://user-images.githubusercontent.com/76792055/103961212-99b8f600-5119-11eb-9900-636fa7fa70aa.mp4

Video didn't capture me in the edit window, but as shown, you can't change what's on screen after editing a song's visibility.

Also, when doing this, the program won't save the changes if you edit the visibility again, no matter if the song is marked as visible or not.

**Comment by Deinonychus71** [comment]
Can't reproduce at this time, feel free to reopen if you can reproduce again!

**Comment by Deinonychus71** [comment]
Reopening as I randomly reproduced the bug recently

**Comment by Deinonychus71** [comment]
That bug should be fixed. Up for testing as part of 1.54b. Closing.
