### ISSUE TITLE
Enhancement: Playback volume in GUI Adjusts Based Upon Volume Setting

### ISSUE THREAD

**Issue by tawawy** [Deinonychus71/Sma5hMusic#26]
Basically, increasing or lowering the playback volume in the GUI based on the song's individual volume setting for ingame playback, to give a a sense of what songs may end up being too loud or quiet when in use.

**Comment by Deinonychus71** [comment]
While I would love to get it to work i don't have enough information currently. Increasing or lowering a value arbitrarily in the GUI would not necessarily result in the same increase/decrease in game.
It'd be great to get the top/bottom volume values in game, then I can do some tests.

**Comment by Deinonychus71** [comment]
Working on a proposition #42
