### ISSUE TITLE
Add Support for Editing Menu Start Points

### ISSUE THREAD

**Issue by TripleLJ** [Deinonychus71/Sma5hMusic#33]
Add support for editing a specific song's menu start points. This effects the different times in which a song will start when returning to the main menu. Can be edited under the ui_bgm_db.prc file under stream property. Some parameter in either the nus3bank or the bgm_property.bin regarding the song length also needs to be edited to work properly.

**Comment by Deinonychus71** [comment]
Happy to do it but I definitely need some documentation. If you know what
all is needed can provide documentation or ping me on discord?

**Comment by Segtendo** [comment]
I mean... they should be able to be edited already. Haven't tested, but here's some info.

The menu start points seem to be stored in the `stream property` section of the `ui_bgm_db`, and can be found with the advanced options enabled in Sma5hMusic. You can have up to five (0-4).

A good example to check is the menu theme for Smash 4 (crs01_menu).
![image](https://user-images.githubusercontent.com/76792055/111243469-288d3780-85cf-11eb-83d4-ee57284044d3.png)

If I recall, `suddendeath` is used for, well, when the song starts during sudden death. `transition` is used for stage morphing, I believe. As you see, on the side, there's five different starting points to the song.

**Comment by Deinonychus71** [comment]
Thank you @Segtendo , I'll add proper descriptions & checks as part of the next release.
