### ISSUE TITLE
auto-organize via game title

### ISSUE THREAD

**Issue by Demonslayerx8** [Deinonychus71/Sma5hMusic#35]
As title suggest. Latter being able to organize the song playlist automatically instead of doing it all manually when you have a lot of songs added, which is quite a pain to do.

**Comment by Deinonychus71** [comment]
We can have some stuff which automatically sort the songs next to their series/games, but multiple drag & drop looks very complicated at this time for very little gain.
Like add a new song, pick a game title, it orders it after the last song that has same series/game title for example.

**Comment by Deinonychus71** [comment]
Removing "Add ability to multi-add/drop songs into a playlist"
Will do auto-organize by game title

**Comment by Deinonychus71** [comment]
A tree view and auto-mapping was implemented as part of 1.54b. Closing.
