### ISSUE TITLE
BRSTM conversion issue crashing Atmosphere ingame

### ISSUE THREAD

**Issue by tawawy** [Deinonychus71/Sma5hMusic#36]
I think that the problem may be how v1.2 (not the beta) handles the "fallback" conversion method for unusual sample rates, but with this BRSTM ( http://www.smashcustommusic.net/song/23421 ) the program consistently provides a corrupted nus3audio in ArcOutput, despite previewing the song correctly, and the BRSTM itself playing correctly when opened. Beyond that, playing BRSTMs with the issue one after another ingame has them seemingly play correctly, but then crash Atmosphere.

**Comment by Deinonychus71** [comment]
After troubleshooting it was discovered that 24khz songs are making the game crash. Will add a check in GUI before the work on #11
