### ISSUE TITLE
Add check when compiling mod

### ISSUE THREAD

**Issue by Demonslayerx8** [Deinonychus71/Sma5hMusic#47]
Add a check or warning system for songs that have no gametitle or series added to the imported song. Have seen quite a bit of people not adding a gametitle or game series to the added song, thus having their song not show up in game.

#Don'tUnderestimateNoobs

**Comment by Deinonychus71** [comment]
There should already be a check though. You can't save changes if no game title is found.
Or is that now a bug?

**Comment by Deinonychus71** [comment]
Closing, feel free to reopen if that's still an issue.
