### ISSUE TITLE
Multi-Select

### ISSUE THREAD

**Issue by confused-student** [Deinonychus71/Sma5hMusic#48]
at the moment, when editing playlists and adding songs you can only add them one by one, when adding more than a few songs this can get very time consuming and tedious when you cant to add songs to multiple stage playlists, the ability to select, drag, and drop multiple songs into a playlist at once would greatly reduce the time it takes to edit multiple playlists.

**Comment by Deinonychus71** [comment]
I'll keep that as enhancement but I already lost my nerves once trying to support it.
But i'd definitely be a great improvement, no doubt.

**Comment by Deinonychus71** [comment]
Implemented for testing as part of 1.54b. Closing.
