### ISSUE TITLE
Music Not Appearing

### ISSUE THREAD

**Issue by jozz024** [Deinonychus71/Sma5hMusic#50]
The music I added is not appearing in the stage song select, but is appearing in the vault, is there a solution to this?

**Comment by Deinonychus71** [comment]
Have you added them to playlists? They won't appear in stages otherwise.
I suggest you ask on the discord channel for regular usage. I will keep this section clean for bugs/feature requests.

**Comment by Deinonychus71** [comment]
Closing, if you still have the issue feel free to reopen.

**Comment by Deinonychus71** [comment]
Just found out there was a bug introduce in 1.42, you want to check on is_selected_original (advanced menu). Sorry about that.
I'll add a function in tools to autofix soon.
