### ISSUE TITLE
Application not starting

### ISSUE THREAD

**Issue by Cyrochek** [Deinonychus71/Sma5hMusic#51]
The application will not run whatsoever. I have followed the steps to put the files in the right place but nothing comes up, not even an error message. Please help, how do I make it work?

**Comment by Deinonychus71** [comment]
Does it generate a log file?

**Comment by Cyrochek** [comment]
I don't think so. As I stated before, nothing pops up but if it does generate one, where do I find it? . Sorry about this issue. @Deinonychus71

**Comment by Cyrochek** [comment]
I haven't found any files that can be a log file unless its stored somewhere else?

**Comment by Deinonychus71** [comment]
Im honestly not sure how to help. It certainly havent happened before as
far as I know. Did you ask on discord?

**Comment by Cyrochek** [comment]
I did, but they either never got to my question or just honestly didn't know what was wrong. They told me to run through administrator or cmd, but both don't work. Its really confusing.  I don't know if I'm missing a software in my pc that can help run it but its weird.

**Comment by Deinonychus71** [comment]
If you're on windows 10 it should just work. You don't need to install another framework or anything. You just need to make sure all the dependencies are there.
If you forgot something in /Games, it would still start but give you an error. The fact that you don't even get that is weird. One of the very first things it does is creating a log file in a Log folder.

And I suppose you have a clean OS install, without some weird customizations on path, like you have a regular temp folder, swap file all of that?

Can you try downloaded the oldest release, see if it starts? Don't need to add the game resources for now, just check if the application does anything.

**Comment by Cyrochek** [comment]
I'm actually on windows 7 Ult., so maybe that's the reason? If not, then nothing has been swapped and I don't have any custom paths on in. Heck, I don't even see a log folder generated when starting in the latest release. I have tried the oldest release (1.0) but they only appear as  .csproj or .cs files and I can't seem to open them. I think based on what you said, its just my PC needing software installations or just a complete upgrade but I don't know honestly.

**Comment by Deinonychus71** [comment]
I've never tested this app on Windows 7. You might need some extra fluff to
make it work.
I can try to run a VM with 7 when I get the time and see, sadly i'm very
busy currently.

**Comment by Cyrochek** [comment]
Oh I see. I think I'll just wait till I upgrade to win10, that's probably the reason why it won't start on win7, but if you do get the chance to test it, I would definitely like to know the results if its possible. Thanks for helping me out and sorry about this mess.
