### ISSUE TITLE
Multi selecting songs to drag a lot of them a the same time (most notably to put them in a playlist)

### ISSUE THREAD

**Issue by Zenobia54** [Deinonychus71/Sma5hMusic#52]
Dragging each song one by one is really tedious, a multi selecting tool would be incredibly helpful

Maybe by pressing CTRL you could enable multi selecting or smth ?

Thank you

**Comment by Zenobia54** [comment]
This would also help assigning incidence and everything, truly a must have

**Comment by Deinonychus71** [comment]
Hi, this was already requested and I'm aware it's tedious. It might just take a while as it's not as simple as it sounds and I'm currently working on something else.
However, in the meantime and although it's not as efficient, you can copy/past incidence with right click.

**Comment by Deinonychus71** [comment]
duplicate of #48

**Comment by Deinonychus71** [comment]
Implemented for testing as part of 1.54b
