### ISSUE TITLE
Adding songs to "All Songs" selection (Battlefield and FD)

### ISSUE THREAD

**Issue by calvinhobbes1010** [Deinonychus71/Sma5hMusic#56]
I've noticed that when adding custom songs to stage playlists, not all of them seem to appear when I try to pick them from the "all songs" list when I play on Battlefield or Final Destination, even if those songs are already assigned to a playlist. Is there a special playlist for this, or do I need to assign every single custom song to a stage/playlist for it to work?

(Likely a "question" or "good first issue" label)

**Comment by Deinonychus71** [comment]
I believe the songs need to be in a playlist associated to a stage to work. I haven't personally looked into it much but that's the behavior I've been noticing.

**Comment by Deinonychus71** [comment]
A solution was implemented as part of 1.54b
