### ISSUE TITLE
Hiding Music

### ISSUE THREAD

**Issue by Jmar00** [Deinonychus71/Sma5hMusic#73]
This is more of a question than an issue. Is it possible to hide or get rid of songs that you don't want to see on a playlist? I added all my custom songs to the Smash Bros Series playlist. They go from  36-76. Is there a way to hide the first default 36 songs or would deleting them hurt anything?

**Comment by Deinonychus71** [comment]
there is an eye icon option to hide songs from within a playlist.
I suggest you ask on discord for specific questions, this is really more to report issues
