### ISSUE TITLE
Error while locating the volume offset in the nus3bank

### ISSUE THREAD

**Issue by YPLovern** [Deinonychus71/Sma5hMusic#74]
[log.20211030.txt](https://github.com/Deinonychus71/Sma5hMusic/files/7446130/log.20211030.txt)
Despite the error, it creates the files and the modded songs work, but the volume remains unchanged from its original state.
There are multiple builds in the log file and every time each song has the error: 

[Sma5h.Mods.Music.Interfaces.INus3AudioService]    [0]    Error while locating the volume offset in the nus3bank

**Comment by Deinonychus71** [comment]
Since it happens on every one of your songs i'm going to assume the problem lies with your template.nus3bank. Have you tried using another one or specifically the one mentioned in the setup?

**Comment by YPLovern** [comment]
Sorry for the wait, yes the template was the issue. Downloading a pre-made resources package fixed the issue.
