### ISSUE TITLE
Changes to Core Songs don't save / revert to filename.

### ISSUE THREAD

**Issue by ElaineLMN** [Deinonychus71/Sma5hMusic#75]
After changing any metadata (title, author, etc.) of a core song, I close the program and when I return, the metadata is completely cleared, with the title reverted to "ui_bgm_[filename]." Any solutions?
![data](https://user-images.githubusercontent.com/93639756/140019006-805ad424-07b5-43b6-ab60-58a22fd7c637.png)

**Comment by Deinonychus71** [comment]
What version are you running? This was a problem in 1.60b but was confirmed fixed in 1.61b

**Comment by ElaineLMN** [comment]
1.60. It appears I need to update. I was unaware I didn't have the newest version.
