### ISSUE TITLE
When Sm5sh Music crashes, all songs in the ui_none Series are deleted.

### ISSUE THREAD

**Issue by SemiEmfi** [Deinonychus71/Sma5hMusic#79]
I dont think i can explain this better than the title does. Its becoming a real issue though, for many reasons.

**Comment by Deinonychus71** [comment]
There's really nothing that can be done with so little information.

Please review "how to create a bug" and at least provide reproduction steps, any modified files you might be using etc.
I'm also not sure what you mean by ui_none songs being deleted.

**Comment by Deinonychus71** [comment]
Closing as there was no response. If you have additional info to provide/repro steps/video please reopen
