### ISSUE TITLE
How do you edit an already made mod?

### ISSUE THREAD

**Issue by Stack3r** [Deinonychus71/Sma5hMusic#81]
I recently created a massive song pack with 360+ songs and somehow my entire Sma5h folder got deleted but I still have the complete mod on my switch, how do I add it back to Sma5h so that I can edit it again. I really don't want to remake the entire mod custom games/names and all

**Comment by Deinonychus71** [comment]
Although it's not recommended you can always use your modified files as source (put them in resources/game) it's not as bad since the game isn't actively being developed anymore.
But still not ideal.
