### ISSUE TITLE
Having trouble updating to new version

### ISSUE THREAD

**Issue by mello0** [Deinonychus71/Sma5hMusic#82]
I've been trying to get help on this but I've barely gotten any answers so I figured I should probably raise them here. I used this program a lot when it was on around v1.52 and since Smash is done with big updates I've been trying to update to the new version. However, when I try to drop my old mods into the new program, I get the error "There was a general exception during init. Object reference not set to an instance of an object". 

I tried to take out each of the files I have inside the mod folder, and after that it seemed like the metadata_mod.json file is what is stopping it from opening. However, I have no clue what's wrong with it and haven't been able to find any information on how to fix the issue.

**Comment by Deinonychus71** [comment]
Can you send me your metadata_mod.json file?

**Comment by Deinonychus71** [comment]
Closing as there's been no answer. If you believe you can send me the files/info to reproduce please reopen
