### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by SeraphYears** [Deinonychus71/Sma5hMusic#83]
![image](https://user-images.githubusercontent.com/82191365/147860125-9ceefc3c-cf51-459e-b4e2-e728ef48c8e6.png)

**Comment by Deinonychus71** [comment]
Please refer to how to create an issue

**Comment by Deinonychus71** [comment]
Closing as there was no response. If you can provide enough information to reproduce please reopen.
