### ISSUE TITLE
Adding Final Fantasy VII songs fails to add them to Northern Cave.

### ISSUE THREAD

**Issue by DShip91** [Deinonychus71/Sma5hMusic#85]
This is just bizarre, I added five songs to the Final Fantasy VII playlist. They load in Midgar just fine but not in Northern Cave despite nothing in the GUI or the output param file. I tried again after resetting the playlist and this time it deleted every song from the Northern Cave stage. I definitely didn't do anything different and both the app and the GUI insist that nothing is out of the ordinary so I'm at a loss here.

**Comment by DShip91** [comment]
I should mention that every other added song in every other stage loads just fine, only Northern Cave is giving me trouble.

**Comment by Demonslayerx8** [comment]
You also need to add em to "Final Fantasy (Sephiroth)" which is for Northern Cave.

**Comment by DShip91** [comment]
Okay. Thanks for letting me know.

**Comment by DShip91** [comment]
Um, where can I find the Sephiroth playlist?

**Comment by Demonslayerx8** [comment]
![image](https://user-images.githubusercontent.com/17195757/147893810-3ba285ed-9db7-4dbd-a111-4d9f2b090450.png)

**Comment by DShip91** [comment]
![Screenshot (121)](https://user-images.githubusercontent.com/79122182/147893855-7579ae57-3de6-4148-b2aa-16d0eff91fc4.png)
Yeah, um, it's not there.

**Comment by Deinonychus71** [comment]
Your game resource files are either not up to date or modified, make sure
you use the latest official resource files. (v?? should display the game
version)

**Comment by Demonslayerx8** [comment]
yeah looks like he's using modified files, mostly ui_bgm_db.prc. Grab a clean one and try again.

**Comment by DShip91** [comment]
That did the trick. Thank you.

**Comment by DShip91** [comment]
It didn't do the trick. I thought it was going to work but now none of my added songs are showing up anywhere.
