### ISSUE TITLE
Minor typo in error message when msg_bgm+us_en.msbt isn't present

### ISSUE THREAD

**Issue by Pacil142857** [Deinonychus71/Sma5hMusic#89]
I was helping someone set up Sma5hMusic. Instead of having `msg_bgm+us_en.msbt` in the resource files, they had `msg_bgm.msbt`, so Sma5hMusic couldn't detect it. That's fine on its own, but they said that they got an error message that said this:
```
The default locale English (US) was not properly loaded.
Verify that msbt_bgm+us_en.msbt is in your resource files or change the defaut locale.
```
There was a bit more to the error message, but the important part is that the error message says to verify that `msbt_bgm+us_en.msbt` is in the resource files, when it should really be `msg_bgm+us_en.msbt` (instead of the first part saying `msg`, the error message wrongly says `msbt`). This isn't a huge issue, but it's worth fixing.

**Comment by Deinonychus71** [comment]
Thank you for the report, i'll update it for the next release ! :)
