### ISSUE TITLE
Cannot download latest version

### ISSUE THREAD

**Issue by Jaster789** [Deinonychus71/Sma5hMusic#90]
![Bruh](https://user-images.githubusercontent.com/82300538/155492353-d0a68bd7-ba97-439a-bed9-fffb3a23d4d8.JPG)
When I try to download the latest version I consistently get told by my anti-virus that their is malware and I rather not risk it and just turn it off.

**Comment by Deinonychus71** [comment]
it's a false positive. If you don't trust the binaries feel free to compile the code yourself. Not much I can do about it.
