### ISSUE TITLE
Wrongly Assigned Author Data in Built "msg_bgm+us_en.mbst"

### ISSUE THREAD

**Issue by ElaineLMN** [Deinonychus71/Sma5hMusic#94]
In the last few builds of my ongoing music expansion project, I noticed that some songs would have seemingly random author data (i.e. "Arrangement: Jules Conroy" or "From Mario & Luigi: Paper Jam") where there should be none. This only happened on modded songs where no text should've been displayed in that field. Upon some digging around in the prc and mbst files, I found that while the prc files was assigning information correctly, the mbst file created by Sma5hMusic (specifically msg_bgm+us_en.mbst) would place seemingly random info from, and only from, other modded songs. Songs always have THE SAME wrong information, build after build, so the it's coming from the same place, wherever that is. I still don't know what ties the 99 songs afflicted together, and did not have this bug until recently. I tried to "fix" the issue by inputting a bunch of spaces in the Author field, which sort of worked, kind of: It led to DIFFERENT songs being afflicted.

**Comment by ElaineLMN** [comment]
More details after further testing: Songs always have THE SAME wrong information, build after build, so the it's coming from the same place, wherever that is. I still don't know what ties the 99 songs afflicted together.

**Comment by Deinonychus71** [comment]
Hm can you try clearing cache and build again?

**Comment by ElaineLMN** [comment]
Might be a dumb question... how do I clear the cache? Just delete the "Cache" folder?

**Comment by ElaineLMN** [comment]
Ok, deleted the cache folder and rebuilt. Problem remained.

**Comment by Deinonychus71** [comment]
I'm really not sure then. Unless you've got conflicting mods. Try disable
every other mod. If it still happens you might need to send me a small
sample that reproduces the issue.

**Comment by ElaineLMN** [comment]
When you say "small sample," what would you need?

**Comment by Deinonychus71** [comment]
I mean a mod folder thats small enough for sharing but reproduce the issue
you're having.
I must say this is the first time Im hearing of something like that.
Especially the randomness of it.

**Comment by ElaineLMN** [comment]
[Mods.zip](https://github.com/Deinonychus71/Sma5hMusic/files/8191474/Mods.zip)
[ArcOutput.zip](https://github.com/Deinonychus71/Sma5hMusic/files/8191475/ArcOutput.zip)

These should do? Mods.zip is the file that goes in the Sma5hMusic folder, where as ArcOutput is from my Switch's SD. Both are without NUS3AUDIOs or NUS3BANKs, since the issue is with metadata.

**Comment by Deinonychus71** [comment]
If you can please try to get a smaller number of songs, it's going to be a
lot faster if there aren't as many entries.
Also please give me one example (id) of a song that has a problem in your
pack.

**Comment by ElaineLMN** [comment]
I can tell you exactly which songs are affected. I looked through the JSONs myself, and there doesn't appear to be anything wrong with them. If you want just one to examine, try "Sinking in Quicksand!" (bgm_mro_mlpj_quicksand). I recommend this one because it's one of the few that I can nail down exactly which entry it's pulling the incorrect data FROM: "Come On!" (bgm_mro_mlpj_comeon). 

Like I said, I checked the JSONs and those all seem fine, which means the problem is happening somewhere in the building process? Checked my logs though, and I didn't see anything that may have happened. I did another build today (same issues), mostly so I had a log to send that was JUST a build. I'll also update this shortly with a full list of every affected song, their IDs, and what song they **_are_**/_**could be**_ pulling from.

[log.20220305.txt](https://github.com/Deinonychus71/Sma5hMusic/files/8191847/log.20220305.txt)

**Comment by ElaineLMN** [comment]
Update: Here's that list I mentioned I would make in the previous comment: [Link](https://docs.google.com/spreadsheets/d/1dTF1Eo9D8DhJAz-sC6xO5Fk86oY1Q5KupsenI6VnBZo/edit?usp=sharing)

**Comment by Deinonychus71** [comment]
Ill give it a look when I can!

**Comment by ElaineLMN** [comment]
Ok! Thank you for your help on this btw! Sorry for being such a novice, but I'll do whatever you need as best I can!

**Comment by Deinonychus71** [comment]
Having a hard time reproducing as the tool will remove songs automatically if their nus3audio aren't found. The building process also requires the files to be there. I would have to modify the tool just to be able to test, and then it would be different code anyway.

It would be faster if you could make a copy of your folder and really delete all the songs that are working well, so I can focus only on one example that isn't working.

**Comment by ElaineLMN** [comment]
Ok, so issue: The number of songs in the pack seems to affect which songs are affected and where they get the incorrect data from, meaning the only way to perfectly replicated would be to give you the pack in full. Would there be a way to just assign the same NUS3AUDIO to all the entries, since the glitch is just with audio? Otherwise I have no clue what songs would be affected, IF they would be affected, and where they'd be pulling their data from.

**Comment by ElaineLMN** [comment]
In any case, here are the NUS3AUDIOs that are 1. related to the issue and 2. we know the source of the wrong information. I'm hoping this will force the issue to happen in the same way, but no guarantees. This folder goes in the MusicMods folder for Sma5hMusic.

 [asum.zip](https://drive.google.com/file/d/1SdctNxyY6gP1bwXqiBGNQzfKnH9-0T7h/view?usp=sharing)

**Comment by ElaineLMN** [comment]
Solved over discord, had to do with modded MBST files in the resources folder. Be sure to add the region to your file names!
